config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :albums
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, :genre, :artist, :year, :length, :tracks, presence: true
  validates :title, :genre, :artist, :length, length: { minimum: 1 }
  validates :title, uniqueness: { scope: :artist }
  validates :length, numericality: { only_integer: true, greater_than: 1 }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all 
  end
  def new
    @album = Album.new
  end
  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end
  def destroy
    @album = get_album
    @album.destroy!
    redirect_to albums_path
  end
  def show
    @album = get_album
  end
  def edit
    @album = get_album
  end
  def update
    @album = get_album
    if @album.update_attributes(album_params)
      redirect_to albums_path
    else
      render :show
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :artist, :genre, :year, :length, :tracks)
  end
  def get_album 
    @album = Album.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<% @title =  "Albums" %>
<h1>All Albums</h1>
<%= link_to "Add New Album", new_album_path %>

<ul>
  <% @albums.each do |a| %>
    <li>
      <%= a.title %>

      -

      <%= a.artist %>

      -

      <%= a.genre %>

      -

      <%= a.year %>

      -

      <%= a.length %>

      -

      <%= a.tracks %>

      -

      -
      <%= link_to "Delete", album_path(a), :method => :delete %>

      -

      -

      <%= link_to "Edit", album_path(a), :method => :get %>
    </li>
  <% end %>
</ul>

app/views/albums/new.html.erb
<% @title = "Add An Album" %>

<h1>Add A New Album</h1>

<%= form_for @album do |a| %>
  <% if @album.errors.full_messages.present? %>
    <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= a.label :title %>
    <%= a.text_field :title %>
  </div>
  <div>
    <%= a.label :artist %>
    <%= a.text_field :artist %>
  </div>
  <div>
    <%= a.label :genre %>
    <%= a.text_field :genre %>
  </div>
  <div>
    <%= a.label :year %>
    <%= a.text_field :year %>
  </div>
  <div>
    <%= a.label :length %>
    <%= a.text_field :length %>
  </div>
  <div>
    <%= a.label :tracks %>
    <%= a.text_field :tracks %>
  </div>

  <div>
    <%= a.submit "Add Album" %>
    <%= link_to "Back To Albums", albums_path%>
  </div>
<% end %>

app/views/albums/show.html.erb
<% @title =  "Edit Album" %>

<h1>Edit Album</h1> 

<%= form_for @album do |a| %>
  <% if @album.errors.full_messages.present? %>
    <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= a.label :title %>
    <%= a.text_field :title %>
  </div>
  <div>
    <%= a.label :artist %>
    <%= a.text_field :artist %>
  </div>
  <div>
    <%= a.label :genre %>
    <%= a.text_field :genre %>
  </div>
  <div>
    <%= a.label :year %>
    <%= a.text_field :year %>
  </div>
  <div>
    <%= a.label :length %>
    <%= a.text_field :length %>
  </div>
  <div>
    <%= a.label :tracks %>
    <%= a.text_field :tracks %>
  </div>

  <div>
    <%= a.submit "Edit Album" %>
    <%= link_to "Back To Albums", albums_path%>
  </div>
<% end %>

app/views/home/index.html.erb
<% content_for :title, "Manage Your Collection!" %>
<div class="home__box">

  <h1>MANAGE YOUR ALBUMS YO</h1>

  <%= link_to 'Albums', albums_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Album Manager" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>